from __future__ import annotations

import os
import re
import subprocess
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .models import Finding, ScanResult
from .scope import apply_finding_scope, classify_path_scope, finding_scope, normalize_path

SCHEMA_VERSION = 'reachability-context-v1'
MAX_CONTEXT_FILE_BYTES = 1_000_000
DEFAULT_RECENT_DAYS = 30
ENTRYPOINT_WINDOW = 80
UNTRUSTED_WINDOW = 25
DEPENDENCY_SOURCES = {'pip-audit', 'dependency-manifest', 'snyk'}
HIGH_EXPLOITABILITY_CWES = {'CWE-22', 'CWE-78', 'CWE-79', 'CWE-89', 'CWE-94', 'CWE-502', 'CWE-918'}

HANDLER_PATH_PATTERNS = (
    re.compile(r'(^|/)(api|apis|route|routes|router|routers|controller|controllers|handler|handlers|views|viewsets)(/|\.|$)', re.I),
    re.compile(r'(^|/)(pages/api|app/api)(/|$)', re.I),
)
HANDLER_LINE_PATTERNS = (
    re.compile(r'@\w*\.(get|post|put|patch|delete|route)\s*\(', re.I),
    re.compile(r'\b(app|router|server)\.(get|post|put|patch|delete|all|use)\s*\(', re.I),
    re.compile(r'\bhttp\.HandleFunc\s*\(|\bhttp\.Handle\s*\(', re.I),
    re.compile(r'\bfunc\s+\w+\s*\([^)]*http\.ResponseWriter[^)]*\*http\.Request', re.I),
    re.compile(r'\b(gin|echo|fiber)\.\w*Context\b|\*\s*(gin|echo)\.Context\b', re.I),
    re.compile(r'@(RequestMapping|GetMapping|PostMapping|PutMapping|PatchMapping|DeleteMapping|RestController|Controller)\b'),
    re.compile(r'\bclass\s+\w+Controller\b|\bHttpServletRequest\b'),
    re.compile(r'\[(HttpGet|HttpPost|HttpPut|HttpPatch|HttpDelete|Route|ApiController)\]', re.I),
    re.compile(r'\b(get|post|put|patch|delete)\s+[\'"/:]', re.I),
    re.compile(r'\bRoute::(get|post|put|patch|delete|any)\s*\(', re.I),
)
UNTRUSTED_PATTERNS = (
    re.compile(r'\b(request|req)\.(args|form|json|body|query|params|headers|cookies|files|GET|POST)\b', re.I),
    re.compile(r'\brequest\.(GET|POST|FILES|headers|cookies|body|json|args|form)\b'),
    re.compile(r'\bparams\b|\bparam\s*\(|\bquery_params\b|\brequest\.data\b', re.I),
    re.compile(r'\$_(GET|POST|REQUEST|COOKIE|FILES|SERVER)\b'),
    re.compile(r'\b(input|raw_input)\s*\(', re.I),
    re.compile(r'\bHttpServletRequest\b|\bRequest\b|\bHttpRequest\b', re.I),
)
GENERATED_MARKERS = (
    'generated by', 'do not edit', 'auto-generated', 'autogenerated', '@generated',
    'code generated', '<auto-generated',
)


@dataclass
class FileContext:
    path: str
    scope: str
    exists: bool = False
    generated_marker: bool = False
    handler_path: bool = False
    handler_lines: list[int] = field(default_factory=list)
    untrusted_lines: list[int] = field(default_factory=list)
    changed: bool = False
    recently_changed: bool = False


def apply_reachability_context(target: Path, scan: ScanResult) -> ScanResult:
    target = target.resolve()
    finding_paths = sorted({normalize_path(finding.location.path) for finding in scan.findings if finding.location.path})
    contexts = build_file_contexts(target, finding_paths)
    new_fingerprints = set(scan.new_findings)
    for finding in scan.findings:
        apply_finding_scope(finding)
        rel = normalize_path(finding.location.path)
        context = contexts.get(rel) or FileContext(path=rel, scope=finding_scope(finding))
        apply_finding_context(finding, context, is_new=finding.fingerprint in new_fingerprints)
    update_reachability_summary(scan)
    return scan


def build_file_contexts(target: Path, paths: list[str]) -> dict[str, FileContext]:
    changed, recent = changed_file_sets(target)
    contexts: dict[str, FileContext] = {}
    root = target.resolve()
    for rel in paths:
        context = FileContext(
            path=rel,
            scope='unknown',
            changed=rel in changed,
            recently_changed=rel in recent,
            handler_path=matches_any(rel, HANDLER_PATH_PATTERNS),
        )
        try:
            path = (root / rel).resolve()
            path.relative_to(root)
        except Exception:
            contexts[rel] = context
            continue
        context.scope = finding_scope_for_path(rel)
        if not path.is_file():
            contexts[rel] = context
            continue
        context.exists = True
        try:
            if path.stat().st_size <= MAX_CONTEXT_FILE_BYTES:
                hydrate_file_context(context, path.read_text(encoding='utf-8', errors='ignore'))
        except OSError:
            pass
        contexts[rel] = context
    return contexts


def finding_scope_for_path(path: str) -> str:
    return classify_path_scope(path)


def hydrate_file_context(context: FileContext, text: str) -> None:
    lines = text.splitlines()
    first_lines = '\n'.join(lines[:25]).lower()
    context.generated_marker = any(marker in first_lines for marker in GENERATED_MARKERS)
    for line_number, line in enumerate(lines, 1):
        if matches_any(line, HANDLER_LINE_PATTERNS):
            context.handler_lines.append(line_number)
        if matches_any(line, UNTRUSTED_PATTERNS):
            context.untrusted_lines.append(line_number)


def apply_finding_context(finding: Finding, context: FileContext, is_new: bool) -> None:
    line = int(finding.location.line or 1)
    near_handler = nearest_line(context.handler_lines, line, ENTRYPOINT_WINDOW)
    near_untrusted = nearest_line(context.untrusted_lines, line, UNTRUSTED_WINDOW)
    scope = context.scope if context.scope != 'unknown' else finding_scope(finding)
    evidence: list[str] = []
    if context.handler_path:
        evidence.append('path matches route/controller/handler convention')
    if near_handler:
        evidence.append(f'HTTP handler pattern near line {near_handler}')
    if near_untrusted:
        evidence.append(f'untrusted request/input pattern near line {near_untrusted}')
    if context.changed:
        evidence.append('changed file context')
    if is_new:
        evidence.append('new since saved baseline')
    if context.recently_changed:
        evidence.append(f'file changed in last {recent_days()} day(s)')
    if context.generated_marker:
        evidence.append('generated-file marker detected')
    evidence.append(f'scope={scope}')

    reachability = classify_reachability(finding, scope, context, bool(near_handler), bool(near_untrusted), is_new)
    exploitability = classify_exploitability(finding, scope, reachability, bool(near_untrusted))
    metadata = dict(finding.scanner_metadata or {})
    metadata.update({
        'source_reachability_context': reachability,
        'source_exploitability_context': exploitability,
        'reachability_evidence': '; '.join(evidence)[:500],
        'request_handler_context': str(bool(context.handler_path or near_handler)).lower(),
        'untrusted_input_context': str(bool(near_untrusted)).lower(),
        'changed_file_context': str(context.changed).lower(),
        'new_finding_context': str(is_new).lower(),
        'recent_file_context': str(context.recently_changed).lower(),
        'generated_file_context': str(context.generated_marker).lower(),
    })
    finding.scanner_metadata = metadata
    if finding.source not in DEPENDENCY_SOURCES or finding.reachability in {'', 'unknown'}:
        finding.reachability = reachability
    if finding.exploitability in {'', 'unknown'} or exploitability_rank(exploitability) > exploitability_rank(finding.exploitability):
        finding.exploitability = exploitability


def classify_reachability(finding: Finding, scope: str, context: FileContext, near_handler: bool, near_untrusted: bool, is_new: bool) -> str:
    if scope in {'test', 'docs', 'example'}:
        return f'non-production-{scope}'
    if scope in {'vendor', 'generated'} or context.generated_marker:
        return 'non-production-generated' if context.generated_marker else f'non-production-{scope}'
    if near_handler and near_untrusted:
        return 'untrusted-entrypoint'
    if near_handler or context.handler_path:
        return 'request-handler'
    if context.changed:
        return 'changed-production-file'
    if context.recently_changed:
        return 'recently-changed-production-file'
    if scope in {'production', 'config'}:
        return 'production-path'
    return finding.reachability or 'unknown'


def classify_exploitability(finding: Finding, scope: str, reachability: str, near_untrusted: bool) -> str:
    if scope in {'test', 'docs', 'example', 'vendor', 'generated'} or reachability.startswith('non-production'):
        return 'low-non-production'
    sensitive = any(cwe.upper() in HIGH_EXPLOITABILITY_CWES for cwe in finding.cwe)
    text = ' '.join([finding.rule_id, finding.title, finding.message, finding.explanation]).lower()
    known_exploit = any(keyword in text for keyword in ('injection', 'traversal', 'deserialization', 'ssrf', 'xss', 'command', 'eval', 'exec'))
    if reachability == 'untrusted-entrypoint' and (sensitive or known_exploit or near_untrusted):
        return 'high-untrusted-input'
    if reachability == 'request-handler' and (sensitive or known_exploit):
        return 'medium-request-adjacent'
    if sensitive or known_exploit:
        return 'medium-exploitable-pattern'
    if reachability in {'changed-production-file', 'recently-changed-production-file', 'production-path'}:
        return 'low-production-context'
    return finding.exploitability or 'unknown'


def update_reachability_summary(scan: ScanResult) -> None:
    scan.summary.reachability_counts = dict(sorted(Counter(finding.reachability or 'unknown' for finding in scan.findings).items()))
    scan.summary.exploitability_counts = dict(sorted(Counter(finding.exploitability or 'unknown' for finding in scan.findings).items()))
    scan.summary.changed_file_findings = sum(1 for finding in scan.findings if (finding.scanner_metadata or {}).get('changed_file_context') == 'true')
    scan.summary.request_handler_findings = sum(1 for finding in scan.findings if (finding.scanner_metadata or {}).get('request_handler_context') == 'true')


def reachability_context_report(scan: ScanResult, limit: int = 100) -> dict[str, Any]:
    update_reachability_summary(scan)
    findings = sorted(scan.findings, key=lambda item: (-item.risk.score, item.location.path, item.location.line, item.id))
    return {
        'schema_version': SCHEMA_VERSION,
        'scan_id': scan.scan_id,
        'project_name': scan.project_name,
        'summary': {
            'reachability_counts': scan.summary.reachability_counts,
            'exploitability_counts': scan.summary.exploitability_counts,
            'changed_file_findings': scan.summary.changed_file_findings,
            'request_handler_findings': scan.summary.request_handler_findings,
        },
        'policy': {
            'raw_code_included': False,
            'handler_window_lines': ENTRYPOINT_WINDOW,
            'untrusted_input_window_lines': UNTRUSTED_WINDOW,
            'recent_change_days': recent_days(),
            'limitations': [
                'Static heuristic context only; not full interprocedural dataflow.',
                'Findings in tests, examples, docs, vendor, or generated files are downranked unless another policy treats them as blocking.',
                'HTTP handler and untrusted input signals are based on path and local source patterns near the finding.',
            ],
        },
        'findings': [finding_context_record(finding) for finding in findings[:max(0, limit)]],
    }


def finding_context_record(finding: Finding) -> dict[str, Any]:
    metadata = finding.scanner_metadata or {}
    return {
        'finding_id': finding.id,
        'fingerprint': finding.fingerprint,
        'source': finding.source,
        'rule_id': finding.rule_id,
        'title': finding.title,
        'location': {'path': finding.location.path, 'line': finding.location.line},
        'scope': finding_scope(finding),
        'reachability': finding.reachability,
        'exploitability': finding.exploitability,
        'risk_score': finding.risk.score,
        'priority': finding.risk.priority,
        'context': {
            'request_handler': metadata.get('request_handler_context') == 'true',
            'untrusted_input': metadata.get('untrusted_input_context') == 'true',
            'changed_file': metadata.get('changed_file_context') == 'true',
            'new_since_baseline': metadata.get('new_finding_context') == 'true',
            'recently_changed': metadata.get('recent_file_context') == 'true',
            'generated_file': metadata.get('generated_file_context') == 'true',
            'evidence': metadata.get('reachability_evidence', ''),
        },
    }


def changed_file_sets(target: Path) -> tuple[set[str], set[str]]:
    env_changed = parse_env_files(os.getenv('SECURE_REVIEW_CHANGED_FILES', ''))
    git_changed, git_recent = git_file_sets(target)
    return env_changed | git_changed, git_recent


def git_file_sets(target: Path) -> tuple[set[str], set[str]]:
    repo_root_result = run_git(target, ['rev-parse', '--show-toplevel'], timeout=5)
    if repo_root_result[0] != 0:
        return set(), set()
    repo_root = Path(repo_root_result[1].strip()).resolve()
    try:
        target_subpath = target.resolve().relative_to(repo_root)
    except Exception:
        target_subpath = Path()
    changed = set()
    for args in (['diff', '--name-only', 'HEAD', '--'], ['diff', '--cached', '--name-only', '--'], ['ls-files', '--others', '--exclude-standard']):
        code, stdout, _stderr = run_git(repo_root, args, timeout=10)
        if code == 0:
            changed.update(normalize_git_files(stdout, target_subpath))
    recent: set[str] = set()
    days = recent_days()
    if days > 0:
        code, stdout, _stderr = run_git(repo_root, ['log', f'--since={days} days ago', '--name-only', '--format=', '--'], timeout=20)
        if code == 0:
            recent.update(normalize_git_files(stdout, target_subpath))
    return changed, recent


def normalize_git_files(stdout: str, target_subpath: Path) -> set[str]:
    files: set[str] = set()
    prefix = normalize_path(str(target_subpath))
    for line in stdout.splitlines():
        item = normalize_path(line)
        if not item:
            continue
        if prefix and prefix != '.':
            if item == prefix:
                files.add(Path(item).name)
            elif item.startswith(prefix + '/'):
                files.add(item[len(prefix) + 1:])
        else:
            files.add(item)
    return files


def parse_env_files(value: str) -> set[str]:
    return {normalize_path(item) for item in re.split(r'[\r\n,;]+', value or '') if normalize_path(item)}


def run_git(cwd: Path, args: list[str], timeout: int) -> tuple[int, str, str]:
    try:
        completed = subprocess.run(['git', '-C', str(cwd), *args], capture_output=True, text=True, timeout=timeout)
        return completed.returncode, completed.stdout, completed.stderr
    except (OSError, subprocess.TimeoutExpired) as exc:
        return 127, '', str(exc)


def nearest_line(lines: list[int], target: int, window: int) -> int | None:
    nearby = [line for line in lines if abs(line - target) <= window or 0 <= target - line <= window]
    return min(nearby, key=lambda item: abs(item - target)) if nearby else None


def matches_any(value: str, patterns: tuple[re.Pattern[str], ...]) -> bool:
    return any(pattern.search(value) for pattern in patterns)


def recent_days() -> int:
    try:
        return max(0, int(os.getenv('REACHABILITY_RECENT_DAYS', str(DEFAULT_RECENT_DAYS))))
    except ValueError:
        return DEFAULT_RECENT_DAYS


def exploitability_rank(value: str) -> int:
    order = {
        'unknown': 0,
        'low-non-production': 1,
        'low-production-context': 2,
        'medium-exploitable-pattern': 3,
        'medium-request-adjacent': 4,
        'high-untrusted-input': 5,
        'reachable-known-vulnerability': 5,
    }
    return order.get(value or 'unknown', 0)
